# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate ``docs/schema-reference.md`` from the code.

The recipe schema is the dataclass tree rooted at :class:`SrtConfig`; the
cluster config (``srtslurm.yaml``) is :class:`ClusterConfig`. This module walks
both and renders one Markdown table per dataclass, so the field-level reference
cannot drift from the code: the checked-in file is regenerated by
``srtctl schema-docs`` and CI fails when it is stale.

The document describes the authoring surface only: every dataclass field a
recipe may set, rooted at ``engine:``, ``roles:`` and the ``placement:`` blocks.
The engine dataclasses carry the recipe's ``roles`` (bound at load) and the
Mooncake master block (filled from ``services:``); a recipe writes neither on
``engine``, so :data:`INTERNAL_FIELDS` leaves them out. The pre-2.0 layout is
documented, for migration only, in the hand-written ``docs/legacy-v1.md``.

Descriptions come from three places, in priority order: an ``Attributes:`` block
in the class docstring (Google style), a string literal directly below a field,
then the ``#`` comment block directly above a field or the trailing comment on
its line. Every authoring field must have one; ``tests/test_schema_docs.py``
fails on a field without a description.

The same walk backs :func:`json_schema` (``srtctl schema``) and the MCP
``explain_field`` tool, so the Markdown tables, the JSON Schema, and the agent
tooling read one source.
"""

from __future__ import annotations

import ast
import inspect
import json
import re
import textwrap
import types
from collections.abc import Mapping, Sequence
from collections.abc import Set as AbstractSet
from dataclasses import MISSING, Field, dataclass, fields, is_dataclass
from pathlib import Path
from typing import Annotated, Any, Literal, cast, get_args, get_origin, get_type_hints

from marshmallow import validate

from srtctl.backends import (
    AtomBackend,
    MockerBackend,
    SGLangBackend,
    TileRTBackend,
    TokenSpeedBackend,
    TRTLLMBackend,
    VLLMBackend,
)
from srtctl.backends.sglang import MooncakeKVStoreConfig
from srtctl.backends.vllm import VLLMMooncakeKVStoreConfig
from srtctl.benchmarks import SHARED_BENCHMARK_FIELDS, get_runner_class, list_benchmarks
from srtctl.core.config import LEGACY_TOP_LEVEL_KEYS
from srtctl.core.formatting import FormattablePath
from srtctl.core.roles import ROLE_NAMES
from srtctl.core.schema import (
    BenchmarkConfig,
    ClusterConfig,
    RoleConfig,
    SrtConfig,
)

_DOCS_DIR = Path(__file__).resolve().parents[3] / "docs"
DEFAULT_OUTPUT = _DOCS_DIR / "schema-reference.md"

GENERATED_NOTICE = (
    "<!-- GENERATED FILE. Do not edit by hand. Regenerate with `srtctl schema-docs`; "
    "CI fails when this file is stale. -->"
)

# backend.type value -> dataclass. Order is the documentation order.
BACKEND_TYPES: tuple[tuple[str, type], ...] = (
    ("atom", AtomBackend),
    ("sglang", SGLangBackend),
    ("tilert", TileRTBackend),
    ("tokenspeed", TokenSpeedBackend),
    ("trtllm", TRTLLMBackend),
    ("vllm", VLLMBackend),
    ("mocker", MockerBackend),
)
_BACKEND_CLASSES: set[type] = {cls for _, cls in BACKEND_TYPES}


@dataclass(frozen=True)
class FieldDoc:
    """One row of a field table."""

    key: str
    type_label: str
    default: str
    description: str
    # Every value the field accepts, from a ``Literal`` annotation or a ``OneOf`` validator; empty when open.
    allowed_values: tuple[Any, ...] = ()


# `engine` is polymorphic on `type`; the generated label would list every engine class.
_ENGINE_ROW = FieldDoc(
    key="engine",
    type_label="str \\| mapping",
    default="optional when every role sets `engine`",
    description=(
        "The engine type (`atom`, `sglang`, `tilert`, `tokenspeed`, `trtllm`, `vllm`, `mocker`) as a string, or a mapping with `type` "
        "plus the engine-wide knobs listed under [Engine types](#engine-types)."
    ),
)

_PLACEMENT_ROWS: tuple[tuple[str, str, str], ...] = (
    ("frontend.placement.node", "`head` \\| `first_decode` \\| `dedicated`", "`head`"),
    ("benchmark.placement.node", "`head` \\| `last_decode` \\| `dedicated`", "`head`"),
    (
        "services[].placement.node",
        "`head` \\| `infra` \\| `dedicated` \\| `prefill` \\| `decode` \\| `agg` \\| `workers`",
        "type default",
    ),
)


# ---------------------------------------------------------------------------
# Type introspection
# ---------------------------------------------------------------------------


def _is_dataclass_type(obj: Any) -> bool:
    return isinstance(obj, type) and is_dataclass(obj)


def _dataclass_targets(annotation: Any) -> list[type]:
    """Dataclass types reachable from an annotation (through Annotated, unions, containers)."""
    if annotation is None:
        return []
    if _is_dataclass_type(annotation):
        return [annotation]
    origin = get_origin(annotation)
    if origin is None:
        return []
    found: list[type] = []
    for arg in get_args(annotation):
        for target in _dataclass_targets(arg):
            if target not in found:
                found.append(target)
    return found


def _is_union(origin: Any) -> bool:
    return origin is types.UnionType or str(origin) == "typing.Union"


def _type_label(annotation: Any, *, markdown: bool = True) -> str:
    """Human-readable type; in Markdown, dataclasses link to their section."""
    if annotation is None:
        return "unknown"
    if annotation is type(None):
        return "None"
    if _is_dataclass_type(annotation):
        return f"[{annotation.__name__}](#{annotation.__name__.lower()})" if markdown else annotation.__name__
    origin = get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))
    if origin is Annotated:  # identity check: str(origin) differs across Python versions
        return _type_label(get_args(annotation)[0], markdown=markdown)
    if origin is Literal:
        quote = "`" if markdown else ""
        return "one of " + ", ".join(f"{quote}{value!r}{quote}" for value in get_args(annotation))
    if _is_union(origin):
        separator = " \\| " if markdown else " | "
        return separator.join(_type_label(arg, markdown=markdown) for arg in get_args(annotation))
    args = get_args(annotation)
    origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
    if not args:
        return origin_name
    if origin is tuple and len(args) == 2 and args[1] is Ellipsis:
        return f"tuple[{_type_label(args[0], markdown=markdown)}, ...]"
    return f"{origin_name}[{', '.join(_type_label(arg, markdown=markdown) for arg in args)}]"


def _literal_values(annotation: Any) -> tuple[Any, ...]:
    """Values of a ``Literal`` annotation (through Annotated and Optional); empty when any member is open."""
    origin = get_origin(annotation)
    if origin is Annotated:
        return _literal_values(get_args(annotation)[0])
    if origin is Literal:
        return get_args(annotation)
    if _is_union(origin):
        values: list[Any] = []
        for member in get_args(annotation):
            if member is type(None):
                continue
            member_values = _literal_values(member)
            if not member_values:
                return ()
            values.extend(member_values)
        return tuple(values)
    return ()


def _validator_values(item: Field) -> tuple[Any, ...]:
    """Choices of a ``OneOf`` validator on the field's marshmallow field, if any."""
    marshmallow_field = item.metadata.get("marshmallow_field")
    for validator in getattr(marshmallow_field, "validators", None) or ():
        if isinstance(validator, validate.OneOf):
            return tuple(validator.choices)
    return ()


def _yaml_key(item: Field) -> str | None:
    """The key a recipe author writes, or None when the field is not user-facing."""
    marshmallow_field = item.metadata.get("marshmallow_field")
    data_key = getattr(marshmallow_field, "data_key", None) if marshmallow_field is not None else None
    if data_key:
        return str(data_key)
    if item.name.startswith("_"):
        return None
    return item.name


def _default_label(item: Field) -> str:
    if item.default is not MISSING:
        return f"`{item.default!r}`"
    if item.default_factory is not MISSING:  # type: ignore[attr-defined]
        factory = item.default_factory  # type: ignore[attr-defined]
        if factory in (dict, list, tuple, set, frozenset):
            return f"`{factory()!r}`"
        name = getattr(factory, "__name__", type(factory).__name__)
        return f"`{name}()`"
    return "required"


# ---------------------------------------------------------------------------
# Descriptions from docstrings and source comments
# ---------------------------------------------------------------------------

_ATTRIBUTE_LINE = re.compile(r"^\s{1,8}([A-Za-z_]\w*)\s*(?:\([^)]*\))?:\s*(.*)$")


def _docstring_attributes(cls: type) -> dict[str, str]:
    """Parse a Google-style ``Attributes:`` block into {field: description}."""
    doc = inspect.getdoc(cls) or ""
    match = re.search(r"^Attributes:\s*$", doc, re.MULTILINE)
    if match is None:
        return {}
    descriptions: dict[str, str] = {}
    current: str | None = None
    for line in doc[match.end() :].splitlines():
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent == 0:
            break
        attribute = _ATTRIBUTE_LINE.match(line)
        if attribute and indent <= 4:
            current = attribute.group(1)
            descriptions[current] = attribute.group(2).strip()
        elif current:
            descriptions[current] = f"{descriptions[current]} {line.strip()}".strip()
    return descriptions


def _comment_descriptions(cls: type) -> dict[str, str]:
    """Comment block above each field, or the trailing comment on its line."""
    try:
        source = textwrap.dedent(inspect.getsource(cls))
    except (OSError, TypeError):
        return {}
    try:
        class_node = ast.parse(source).body[0]
    except (SyntaxError, IndexError):
        return {}
    if not isinstance(class_node, ast.ClassDef):
        return {}
    lines = source.splitlines()
    descriptions: dict[str, str] = {}
    body = class_node.body
    for position, node in enumerate(body):
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        following = body[position + 1] if position + 1 < len(body) else None
        if (
            isinstance(following, ast.Expr)
            and isinstance(following.value, ast.Constant)
            and isinstance(following.value.value, str)
        ):
            descriptions[node.target.id] = " ".join(inspect.cleandoc(following.value.value).split())
            continue
        leading: list[str] = []
        index = node.lineno - 2
        while index >= 0 and lines[index].strip().startswith("#"):
            leading.insert(0, lines[index].strip().lstrip("#").strip())
            index -= 1
        text = " ".join(part for part in leading if part)
        if not text and node.end_lineno is not None and node.end_col_offset is not None:
            tail = lines[node.end_lineno - 1][node.end_col_offset :]
            if "#" in tail:
                text = tail.split("#", 1)[1].strip()
        if text:
            descriptions[node.target.id] = text
    return descriptions


def _descriptions(cls: type) -> dict[str, str]:
    merged = _comment_descriptions(cls)
    merged.update(_docstring_attributes(cls))
    return merged


def _class_summary(cls: type) -> str:
    doc = inspect.getdoc(cls) or ""
    first = doc.split("\n\n", 1)[0].strip()
    return " ".join(first.split())


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def field_docs(cls: Any, *, markdown: bool = True) -> list[FieldDoc]:
    """Field table rows for one dataclass, in declaration order."""
    hints = get_type_hints(cls, include_extras=True)
    descriptions = _descriptions(cls)
    rows: list[FieldDoc] = []
    for item in fields(cls):
        key = _yaml_key(item)
        if key is None:
            continue
        annotation = hints.get(item.name, item.type)
        literal_values = _literal_values(annotation)
        validator_values = _validator_values(item)
        type_label = _type_label(annotation, markdown=markdown)
        if validator_values and not literal_values:
            quote = "`" if markdown else ""
            type_label = "one of " + ", ".join(f"{quote}{value!r}{quote}" for value in validator_values)
        rows.append(
            FieldDoc(
                key=key,
                type_label=type_label,
                default=_default_label(item),
                description=descriptions.get(item.name, ""),
                allowed_values=literal_values or validator_values,
            )
        )
    return rows


def field_annotations(cls: Any) -> dict[str, Any]:
    """YAML key -> type annotation for every user-facing field of ``cls``."""
    hints = get_type_hints(cls, include_extras=True)
    out: dict[str, Any] = {}
    for item in fields(cls):
        key = _yaml_key(item)
        if key is not None:
            out[key] = hints.get(item.name, item.type)
    return out


# ---------------------------------------------------------------------------
# Internal fields: what the authoring vocabularies expand into
# ---------------------------------------------------------------------------


def _present(cls: type, keys: frozenset[str]) -> frozenset[str]:
    """Keep only the keys ``cls`` actually declares (TRT-LLM alone has ``*_extra_args``)."""
    declared = {row.key for row in field_docs(cls)}
    return frozenset(key for key in keys if key in declared)


# Engine dataclass -> yaml keys that are internal (the roles SrtConfig binds, the Mooncake
# block `services:` fills; never written on `engine`). Omitted from schema-reference.md.
INTERNAL_FIELDS: dict[type, frozenset[str]] = {
    cls: _present(cls, frozenset({"roles", "mooncake_kv_store"})) for _, cls in BACKEND_TYPES
}

# Top-level keys the loader gate refuses (the pre-2.0 `backend:` and `infra:`); not fields anymore,
# kept so the recipe table and the gate name the same keys.
INTERNAL_TOP_LEVEL: frozenset[str] = frozenset(LEGACY_TOP_LEVEL_KEYS)

# Dataclasses reachable only through internal keys.
INTERNAL_CLASSES: frozenset[type] = frozenset(
    {
        MooncakeKVStoreConfig,
        VLLMMooncakeKVStoreConfig,
    }
)


def _row(row: FieldDoc) -> str:
    return f"| `{row.key}` | {row.type_label} | {row.default} | {_cell(row.description)} |"


def _table_header() -> list[str]:
    return ["| Key | Type | Default | Description |", "|---|---|---|---|"]


_SCHEMA_ROW_DESCRIPTION = (
    "Recipe schema version. Every recipe declares `schema: 2`; a recipe without it is the pre-2.0 "
    "layout and does not load (see [legacy-v1.md](legacy-v1.md) and `srtctl migrate`)."
)


def authoring_rows(cls: type, *, markdown: bool = True) -> list[FieldDoc]:
    """The rows a recipe (or ``srtslurm.yaml``) may write for ``cls``: internal fields dropped, special rows applied."""
    internal = INTERNAL_FIELDS.get(cls, frozenset())
    if cls is SrtConfig:
        internal = internal | INTERNAL_TOP_LEVEL
    engine_type = _ENGINE_ROW.type_label if markdown else "str | mapping"
    out: list[FieldDoc] = []
    for row in field_docs(cls, markdown=markdown):
        if row.key in internal:
            continue
        if cls is SrtConfig and row.key == "engine":
            row = FieldDoc(row.key, engine_type, _ENGINE_ROW.default, _ENGINE_ROW.description)
        elif cls is RoleConfig and row.key == "engine":
            row = FieldDoc(row.key, engine_type, row.default, row.description)
        elif cls is SrtConfig and row.key == "schema":
            row = FieldDoc(row.key, row.type_label, "required", _SCHEMA_ROW_DESCRIPTION, row.allowed_values)
        out.append(row)
    return out


def _render_table(cls: type) -> list[str]:
    """Field table for ``cls``: every field a recipe may write."""
    return _table_header() + [_row(row) for row in authoring_rows(cls)]


def _render_authoring_surface() -> list[str]:
    lines = [
        "## Authoring surface",
        "",
        (
            "Three vocabularies carry the engine, the topology, and the placement. `engine` and `roles` are "
            "fields of the recipe (the table above and [RoleConfig](#roleconfig) below); the engine dataclasses' "
            "per-mode fields are internal and receive each role's settings at load. The pre-2.0 layout no longer "
            "loads and is documented for migration in [legacy-v1.md](legacy-v1.md)."
        ),
        "",
        "### engine",
        "",
        "`engine: <type>` or `engine: {type: <type>, ...}`. `type` is one of "
        + ", ".join(f"`{name}`" for name, _ in BACKEND_TYPES)
        + "; the remaining keys are that engine's knobs, listed under [Engine types](#engine-types).",
        "Use either one top-level engine or an explicit engine on every role, never both. Role engines do not inherit options from each other.",
        "",
        "### roles",
        "",
        "`roles.<role>` for `" + "`, `".join(ROLE_NAMES) + "`. The `agg` role is the aggregated deployment; "
        "`prefill` and `decode` together are the disaggregated one. Each role is a [RoleConfig](#roleconfig): "
        "`nodes` (or `colocate` on decode, to share the prefill nodes), `workers`, `gpus`, `env`, `args`, and "
        "optionally its own `engine` and `container`.",
        "",
        "### placement",
        "",
    ]
    lines.extend(["| Key | Values | Default |", "|---|---|---|"])
    for key, values, default in _PLACEMENT_ROWS:
        lines.append(f"| `{key}` | {values} | {default} |")
    lines.extend(
        [
            "",
            (
                "`dedicated` reserves a node for that component. The discovery plane (etcd, NATS) is placed "
                "through its `services:` entries; see [services.md](services.md)."
            ),
            "",
        ]
    )
    return lines


def _nested_types(cls: Any) -> list[type]:
    hints = get_type_hints(cls, include_extras=True)
    found: list[type] = []
    for item in fields(cls):
        if _yaml_key(item) is None:
            continue
        for target in _dataclass_targets(hints.get(item.name, item.type)):
            if target not in found:
                found.append(target)
    return found


def _walk(root: type, skip: AbstractSet[type]) -> list[type]:
    """Breadth-first list of dataclasses reachable from ``root`` (root excluded)."""
    order: list[type] = []
    queue = [root]
    seen = {root}
    while queue:
        current = queue.pop(0)
        for nested in _nested_types(current):
            if nested in seen or nested in skip:
                continue
            seen.add(nested)
            order.append(nested)
            queue.append(nested)
    return order


def _render_class_section(cls: type, level: int) -> list[str]:
    heading = "#" * level
    lines = [f"{heading} {cls.__name__}", ""]
    summary = _class_summary(cls)
    if summary:
        lines.extend([summary, ""])
    lines.extend(_render_table(cls))
    lines.append("")
    return lines


def _section_classes() -> tuple[list[type], list[type], list[type]]:
    """Recipe sections, engine-only nested types, and cluster-only nested types, in document order."""
    nested = [cls for cls in _walk(SrtConfig, skip=_BACKEND_CLASSES) if cls not in INTERNAL_CLASSES]
    engine_nested: list[type] = []
    for _, cls in BACKEND_TYPES:
        for extra in _walk(cls, skip=_BACKEND_CLASSES | set(nested)):
            if extra not in engine_nested and extra not in INTERNAL_CLASSES:
                engine_nested.append(extra)
    cluster_nested = _walk(ClusterConfig, skip=_BACKEND_CLASSES | set(nested) | set(engine_nested))
    return nested, engine_nested, cluster_nested


def documented_classes() -> list[type]:
    """Every dataclass with a table in the schema reference, in document order."""
    nested, engine_nested, cluster_nested = _section_classes()
    return [
        SrtConfig,
        *nested,
        *(cls for _, cls in BACKEND_TYPES),
        *engine_nested,
        ClusterConfig,
        *cluster_nested,
    ]


# ``benchmark.type: manual`` has no runner class to describe it.
_MANUAL_BENCHMARK_SUMMARY = "No benchmark client runs; the job serves until it is cancelled or hits its time limit."


def benchmark_types() -> list[tuple[str, str, tuple[str, ...]]]:
    """``(type, summary, fields beyond the shared ones)`` for ``manual`` and every registered runner."""
    rows: list[tuple[str, str, tuple[str, ...]]] = [("manual", _MANUAL_BENCHMARK_SUMMARY, ())]
    for name in list_benchmarks():
        runner = get_runner_class(name)
        if runner is None:
            continue
        own = tuple(sorted(runner.config_fields - SHARED_BENCHMARK_FIELDS))
        rows.append((name, _class_summary(runner), own))
    return rows


def _render_benchmark_types() -> list[str]:
    lines = [
        "#### Benchmark types",
        "",
        (
            "`benchmark.type` selects a runner. Every type accepts the shared keys "
            + ", ".join(f"`{key}`" for key in sorted(SHARED_BENCHMARK_FIELDS))
            + " plus the keys in its row; a recipe that sets any other `benchmark` key fails to load. "
            "Generated from the benchmark registry."
        ),
        "",
        "| Type | Description | Keys beyond the shared ones |",
        "|---|---|---|",
    ]
    for name, summary, own in benchmark_types():
        keys = ", ".join(f"`{key}`" for key in own) or "none"
        lines.append(f"| `{name}` | {_cell(summary)} | {keys} |")
    lines.append("")
    return lines


def render_schema_reference() -> str:
    """Render the field-level reference for recipes and the cluster config."""
    lines: list[str] = [
        "# Schema Reference",
        "",
        GENERATED_NOTICE,
        "",
        (
            "Field-level reference for the recipe layout (`schema: 2`) and the cluster config "
            "`srtslurm.yaml` (`ClusterConfig`), generated from the dataclasses in `srtctl.core.schema` and "
            "`srtctl.backends`. Each table lists the YAML key, "
            "the type, the default (`required` when there is none), and a description taken from the class "
            "docstring or the comment on the field. Nested types link to their own table. The pre-2.0 (v1) "
            "layout no longer loads; its key-by-key mapping onto this layout is in [legacy-v1.md](legacy-v1.md) "
            "and `srtctl migrate` rewrites it. For prose, examples, and semantics see "
            "[config-reference.md](config-reference.md). The same data is available as JSON Schema from "
            "`srtctl schema` and per field from the MCP `explain_field` tool."
        ),
        "",
        "## Recipe",
        "",
        "Top-level keys of a recipe YAML.",
        "",
    ]
    lines.extend(_render_table(SrtConfig))
    lines.append("")
    lines.extend(_render_authoring_surface())

    nested, engine_nested, cluster_nested = _section_classes()
    if nested:
        lines.extend(["## Recipe sections", ""])
        for cls in nested:
            lines.extend(_render_class_section(cls, level=3))
            if cls is BenchmarkConfig:
                lines.extend(_render_benchmark_types())

    lines.extend(
        [
            "## Engine types",
            "",
            "`engine.type` selects one of the following; the remaining `engine` keys are that type's knobs.",
            "",
        ]
    )
    for type_name, cls in BACKEND_TYPES:
        lines.extend([f"### {cls.__name__}", "", f"`engine.type: {type_name}`", ""])
        summary = _class_summary(cls)
        if summary:
            lines.extend([summary, ""])
        lines.extend(_render_table(cls))
        lines.append("")
    for cls in engine_nested:
        lines.extend(_render_class_section(cls, level=3))

    lines.extend(
        [
            "## Cluster config",
            "",
            "Top-level keys of `srtslurm.yaml`. Recipes inherit these defaults and resolve aliases through them.",
            "",
        ]
    )
    lines.extend(_render_table(ClusterConfig))
    lines.append("")
    for cls in cluster_nested:
        lines.extend(_render_class_section(cls, level=3))

    return "\n".join(lines).rstrip() + "\n"


def write_schema_reference(output: Path = DEFAULT_OUTPUT) -> Path:
    """Write the rendered document; return its path."""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_schema_reference(), encoding="utf-8")
    return output


def schema_reference_is_current(output: Path = DEFAULT_OUTPUT) -> bool:
    """True when the checked-in file matches what the code renders."""
    return output.exists() and output.read_text(encoding="utf-8") == render_schema_reference()


# ---------------------------------------------------------------------------
# JSON Schema (``srtctl schema``)
# ---------------------------------------------------------------------------

JSON_SCHEMA_DIALECT = "https://json-schema.org/draft/2020-12/schema"

_JSON_SCALARS: dict[Any, str] = {bool: "boolean", int: "integer", float: "number", str: "string"}
_NO_DEFAULT = object()


def _json_default(item: Field) -> Any:
    if item.default is not MISSING:
        value = item.default
    elif (factory := cast(Any, item.default_factory)) in (dict, list, tuple):
        value = factory()
    else:
        return _NO_DEFAULT
    if isinstance(value, tuple):
        value = list(value)
    if not isinstance(value, str | int | float | bool | list | dict | type(None)):
        return _NO_DEFAULT
    try:
        json.dumps(value)
    except TypeError:
        return _NO_DEFAULT
    return value


def _engine_json(defs: dict[str, Any]) -> dict[str, Any]:
    """An engine is a type name or a mapping; a mapping without ``type`` loads as ``sglang``."""
    options: list[dict[str, Any]] = [{"type": "string", "enum": [name for name, _ in BACKEND_TYPES]}]
    options.extend(_json_type(cls, defs) for _, cls in BACKEND_TYPES)
    return {"anyOf": options}


def _json_type(annotation: Any, defs: dict[str, Any]) -> dict[str, Any]:
    if annotation is Any or annotation is None:
        return {}
    if annotation is type(None):
        return {"type": "null"}
    if annotation in _JSON_SCALARS:
        return {"type": _JSON_SCALARS[annotation]}
    if annotation is FormattablePath:
        return {"type": "string"}
    if _is_dataclass_type(annotation):
        name = annotation.__name__
        if name not in defs:
            defs[name] = {}
            defs[name] = _object_json(annotation, defs)
        return {"$ref": f"#/$defs/{name}"}
    if annotation in (dict, Mapping):
        return {"type": "object"}
    if annotation in (list, tuple):
        return {"type": "array"}
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        return _json_type(args[0], defs)
    if origin is Literal:
        return {"enum": list(args)}
    if _is_union(origin):
        members = [arg for arg in args if arg is not type(None)]
        if any(member in _BACKEND_CLASSES for member in members):
            engine = _engine_json(defs)
            if len(members) < len(args):
                engine["anyOf"].append({"type": "null"})
            return engine
        return {"anyOf": [_json_type(arg, defs) for arg in args]}
    if origin is dict or origin is Mapping or (isinstance(origin, type) and issubclass(origin, Mapping)):
        out: dict[str, Any] = {"type": "object"}
        value = _json_type(args[1], defs) if len(args) == 2 else {}
        if value:
            out["additionalProperties"] = value
        return out
    if origin in (list, tuple, set, frozenset) or (isinstance(origin, type) and issubclass(origin, Sequence)):
        out = {"type": "array"}
        item_type = args[0] if args else Any
        items = _json_type(item_type, defs)
        if items:
            out["items"] = items
        return out
    return {}


# Fields whose loader also accepts a shorthand spelling (a custom marshmallow field or a pre_load hook).
_JSON_SHORTHANDS: dict[tuple[str, str], dict[str, Any]] = {
    ("RoleConfig", "restart"): {"enum": ["never", "on-failure", "always"]},
    ("ServiceConfig", "metrics"): {"$ref": "#/$defs/ServiceMetricsConfig"},
}


def _object_json(cls: type, defs: dict[str, Any]) -> dict[str, Any]:
    annotations = field_annotations(cls)
    items = {_yaml_key(item): item for item in fields(cast(Any, cls))}
    properties: dict[str, Any] = {}
    required: list[str] = []
    for row in authoring_rows(cls, markdown=False):
        prop: dict[str, Any] = dict(_json_type(annotations[row.key], defs))
        if row.allowed_values and not _literal_values(annotations[row.key]):
            prop = {"enum": list(row.allowed_values)}
        if (shorthand := _JSON_SHORTHANDS.get((cls.__name__, row.key))) is not None:
            prop = {"anyOf": [shorthand, prop]}
        if row.description:
            prop["description"] = row.description
        if row.default == "required":
            required.append(row.key)
        else:
            default = _json_default(items[row.key])
            if default is not _NO_DEFAULT:
                prop["default"] = default
        properties[row.key] = prop
    out: dict[str, Any] = {"type": "object", "additionalProperties": False, "properties": properties}
    summary = _class_summary(cls)
    if summary:
        out["description"] = summary
    if required:
        out["required"] = required
    return out


def json_schema(root: type = SrtConfig) -> dict[str, Any]:
    """JSON Schema (draft 2020-12) for a recipe (``SrtConfig``) or ``srtslurm.yaml`` (``ClusterConfig``).

    Built from the same rows as the Markdown reference, so descriptions, defaults, and allowed values match.
    It checks shape only; cross-field rules (topology, placement, benchmark keys per type) stay in
    ``srtctl validate``.
    """
    defs: dict[str, Any] = {}
    body = _object_json(root, defs)
    if root is not SrtConfig:
        title = "srt-slurm cluster config (srtslurm.yaml)"
        return {"$schema": JSON_SCHEMA_DIALECT, "title": title, **body, "$defs": dict(sorted(defs.items()))}

    body["properties"]["sweep"] = {
        "type": "object",
        "description": (
            "Parameter sweep: each key maps to a list of values substituted into `{key}` placeholders; "
            "`srtctl apply` submits one job per combination and drops this block from each."
        ),
        "additionalProperties": {"type": "array"},
    }
    defs["Recipe"] = body
    defs["RecipeBase"] = {key: value for key, value in body.items() if key != "required"}
    # An override file is `base` plus `override_*` / `zip_override_*` variants deep-merged over it. Variants
    # are partial (and zip variants hold lists), so only `base` is checked field by field.
    override_file = {
        "type": "object",
        "required": ["base"],
        "additionalProperties": False,
        "properties": {"schema": body["properties"]["schema"], "base": {"$ref": "#/$defs/RecipeBase"}},
        "patternProperties": {"^(zip_)?override_": {"type": "object"}},
    }
    return {
        "$schema": JSON_SCHEMA_DIALECT,
        "title": "srt-slurm recipe",
        "description": "A recipe, or an override file (`base` plus `override_*` / `zip_override_*` variants).",
        "if": {"type": "object", "required": ["base"]},
        "then": override_file,
        "else": {"$ref": "#/$defs/Recipe"},
        "$defs": dict(sorted(defs.items())),
    }


# ---------------------------------------------------------------------------
# Field lookup (MCP ``explain_field``)
# ---------------------------------------------------------------------------

_SCHEMA_REFERENCE_PATH = "docs/schema-reference.md"
_PATH_SPLIT = re.compile(r"\.|\[\d*\]")


def describe_field(cls: type, row: FieldDoc) -> dict[str, Any]:
    """One field as plain data: the same type, default, description, and values as its schema-reference row."""
    out: dict[str, Any] = {
        "name": row.key,
        "type": row.type_label,
        "default": row.default.replace("`", ""),
        "description": row.description,
        "allowed_values": list(row.allowed_values),
        "defined_in": cls.__name__,
        "reference": f"{_SCHEMA_REFERENCE_PATH}#{cls.__name__.lower()}",
    }
    if cls is BenchmarkConfig and row.key != "type":
        if row.key in SHARED_BENCHMARK_FIELDS:
            out["benchmark_types"] = "all"
        else:
            out["benchmark_types"] = [name for name, _, own in benchmark_types() if row.key in own]
    return out


def _next_candidates(annotation: Any) -> tuple[list[type], bool]:
    """Dataclasses a path may descend into after a field, and whether a map key / list index comes first."""
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        return _next_candidates(args[0])
    if _is_union(origin):
        members = [arg for arg in args if arg is not type(None)]
        if any(member in _BACKEND_CLASSES for member in members):
            return [cls for _, cls in BACKEND_TYPES], False
        out: list[type] = []
        keyed = False
        for member in members:
            found, member_keyed = _next_candidates(member)
            out.extend(cls for cls in found if cls not in out)
            keyed = keyed or member_keyed
        return out, keyed
    if annotation is not FormattablePath and _is_dataclass_type(annotation):
        return [annotation], False
    if args and (origin in (dict, list, tuple) or (isinstance(origin, type) and issubclass(origin, Mapping))):
        element = args[1] if origin is not list and origin is not tuple and len(args) == 2 else args[0]
        found, _ = _next_candidates(element)
        return found, bool(found)
    return [], False


def resolve_field_path(path: str) -> dict[str, Any]:
    """Resolve a dotted recipe path (``roles.decode.nodes``, ``engine.connector``, ``services[0].kind``).

    Returns every segment's field description and the leaf; on failure, the first unknown segment and the
    keys that were valid there.
    """
    segments = [segment for segment in _PATH_SPLIT.split(path.strip()) if segment]
    candidates: list[type] = [SrtConfig]
    expect_key = False
    trail: list[dict[str, Any]] = []
    for segment in segments:
        matches = [
            (cls, row) for cls in candidates for row in authoring_rows(cls, markdown=False) if row.key == segment
        ]
        if expect_key and not matches:
            expect_key = False  # a role name, a mapping key, or a list index
            continue
        if not matches:
            available = sorted({row.key for cls in candidates for row in authoring_rows(cls, markdown=False)})
            return {"segments": trail, "leaf": None, "unresolved": segment, "available": available}
        cls, row = matches[0]
        entry = describe_field(cls, row)
        if len(candidates) > 1 and all(candidate in _BACKEND_CLASSES for candidate in candidates):
            entry["engine_types"] = [name for name, backend in BACKEND_TYPES if any(backend is c for c, _ in matches)]
        trail.append(entry)
        candidates, expect_key = _next_candidates(field_annotations(cls)[segment])
    return {"segments": trail, "leaf": trail[-1] if trail else None, "unresolved": None, "available": []}
