# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate ``docs/schema-reference.md`` from the code.

The recipe schema is the dataclass tree rooted at :class:`SrtConfig`; the
cluster config (``srtslurm.yaml``) is :class:`ClusterConfig`. This module walks
both and renders one Markdown table per dataclass, so the field-level reference
cannot drift from the code: the checked-in file is regenerated by
``srtctl schema-docs`` and CI fails when it is stale.

The document describes the authoring surface only: every dataclass field a
recipe may set, rooted at ``engine:``, ``roles:`` and the ``placement:`` blocks.
The engine dataclasses carry the recipe's ``roles`` (bound at load) and the
Mooncake master block (filled from ``services:``); a recipe writes neither on
``engine``, so :data:`INTERNAL_FIELDS` leaves them out. The pre-2.0 layout is
documented, for migration only, in the hand-written ``docs/legacy-v1.md``.

Descriptions come from two places, in priority order: an ``Attributes:`` block
in the class docstring (Google style), then the ``#`` comment block directly
above a field or the trailing comment on its line.
"""

from __future__ import annotations

import ast
import inspect
import re
import textwrap
import types
from collections.abc import Set as AbstractSet
from dataclasses import MISSING, Field, dataclass, fields, is_dataclass
from pathlib import Path
from typing import Annotated, Any, Literal, get_args, get_origin, get_type_hints

from srtctl.backends import (
    AtomProtocol,
    MockerProtocol,
    SGLangProtocol,
    TileRTProtocol,
    TokenSpeedProtocol,
    TRTLLMProtocol,
    VLLMProtocol,
)
from srtctl.backends.sglang import MooncakeKVStoreConfig
from srtctl.backends.vllm import VLLMMooncakeKVStoreConfig
from srtctl.core.config import LEGACY_TOP_LEVEL_KEYS
from srtctl.core.roles import ROLE_NAMES
from srtctl.core.schema import (
    ClusterConfig,
    RoleConfig,
    SrtConfig,
)

_DOCS_DIR = Path(__file__).resolve().parents[3] / "docs"
DEFAULT_OUTPUT = _DOCS_DIR / "schema-reference.md"

GENERATED_NOTICE = (
    "<!-- GENERATED FILE. Do not edit by hand. Regenerate with `srtctl schema-docs`; "
    "CI fails when this file is stale. -->"
)

# backend.type value -> dataclass. Order is the documentation order.
BACKEND_TYPES: tuple[tuple[str, type], ...] = (
    ("atom", AtomProtocol),
    ("sglang", SGLangProtocol),
    ("tilert", TileRTProtocol),
    ("tokenspeed", TokenSpeedProtocol),
    ("trtllm", TRTLLMProtocol),
    ("vllm", VLLMProtocol),
    ("mocker", MockerProtocol),
)
_BACKEND_CLASSES: set[type] = {cls for _, cls in BACKEND_TYPES}


@dataclass(frozen=True)
class FieldDoc:
    """One row of a field table."""

    key: str
    type_label: str
    default: str
    description: str


# `engine` is polymorphic on `type`; the generated label would list every engine class.
_ENGINE_ROW = FieldDoc(
    key="engine",
    type_label="str \\| mapping",
    default="optional when every role sets `engine`",
    description=(
        "The engine type (`atom`, `sglang`, `tilert`, `tokenspeed`, `trtllm`, `vllm`, `mocker`) as a string, or a mapping with `type` "
        "plus the engine-wide knobs listed under [Engine types](#engine-types)."
    ),
)

_PLACEMENT_ROWS: tuple[tuple[str, str, str], ...] = (
    ("frontend.placement.node", "`head` \\| `first_decode` \\| `dedicated`", "`head`"),
    ("benchmark.placement.node", "`head` \\| `last_decode` \\| `dedicated`", "`head`"),
    (
        "services[].placement.node",
        "`head` \\| `infra` \\| `dedicated` \\| `prefill` \\| `decode` \\| `agg` \\| `workers`",
        "type default",
    ),
)


# ---------------------------------------------------------------------------
# Type introspection
# ---------------------------------------------------------------------------


def _is_dataclass_type(obj: Any) -> bool:
    return isinstance(obj, type) and is_dataclass(obj)


def _dataclass_targets(annotation: Any) -> list[type]:
    """Dataclass types reachable from an annotation (through Annotated, unions, containers)."""
    if annotation is None:
        return []
    if _is_dataclass_type(annotation):
        return [annotation]
    origin = get_origin(annotation)
    if origin is None:
        return []
    found: list[type] = []
    for arg in get_args(annotation):
        for target in _dataclass_targets(arg):
            if target not in found:
                found.append(target)
    return found


def _type_label(annotation: Any) -> str:
    """Human-readable type, with dataclasses linked to their section."""
    if annotation is None:
        return "unknown"
    if annotation is type(None):
        return "None"
    if _is_dataclass_type(annotation):
        return f"[{annotation.__name__}](#{annotation.__name__.lower()})"
    origin = get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))
    if origin is Annotated:  # identity check: str(origin) differs across Python versions
        return _type_label(get_args(annotation)[0])
    if origin is Literal:
        return "one of " + ", ".join(f"`{value!r}`" for value in get_args(annotation))
    if origin is types.UnionType or str(origin) == "typing.Union":
        return " \\| ".join(_type_label(arg) for arg in get_args(annotation))
    args = get_args(annotation)
    origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
    if not args:
        return origin_name
    if origin is tuple and len(args) == 2 and args[1] is Ellipsis:
        return f"tuple[{_type_label(args[0])}, ...]"
    return f"{origin_name}[{', '.join(_type_label(arg) for arg in args)}]"


def _yaml_key(item: Field) -> str | None:
    """The key a recipe author writes, or None when the field is not user-facing."""
    marshmallow_field = item.metadata.get("marshmallow_field")
    data_key = getattr(marshmallow_field, "data_key", None) if marshmallow_field is not None else None
    if data_key:
        return str(data_key)
    if item.name.startswith("_"):
        return None
    return item.name


def _default_label(item: Field) -> str:
    if item.default is not MISSING:
        return f"`{item.default!r}`"
    if item.default_factory is not MISSING:  # type: ignore[attr-defined]
        factory = item.default_factory  # type: ignore[attr-defined]
        if factory in (dict, list, tuple, set, frozenset):
            return f"`{factory()!r}`"
        name = getattr(factory, "__name__", type(factory).__name__)
        return f"`{name}()`"
    return "required"


# ---------------------------------------------------------------------------
# Descriptions from docstrings and source comments
# ---------------------------------------------------------------------------

_ATTRIBUTE_LINE = re.compile(r"^\s{1,8}([A-Za-z_]\w*)\s*(?:\([^)]*\))?:\s*(.*)$")


def _docstring_attributes(cls: type) -> dict[str, str]:
    """Parse a Google-style ``Attributes:`` block into {field: description}."""
    doc = inspect.getdoc(cls) or ""
    match = re.search(r"^Attributes:\s*$", doc, re.MULTILINE)
    if match is None:
        return {}
    descriptions: dict[str, str] = {}
    current: str | None = None
    for line in doc[match.end() :].splitlines():
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent == 0:
            break
        attribute = _ATTRIBUTE_LINE.match(line)
        if attribute and indent <= 4:
            current = attribute.group(1)
            descriptions[current] = attribute.group(2).strip()
        elif current:
            descriptions[current] = f"{descriptions[current]} {line.strip()}".strip()
    return descriptions


def _comment_descriptions(cls: type) -> dict[str, str]:
    """Comment block above each field, or the trailing comment on its line."""
    try:
        source = textwrap.dedent(inspect.getsource(cls))
    except (OSError, TypeError):
        return {}
    try:
        class_node = ast.parse(source).body[0]
    except (SyntaxError, IndexError):
        return {}
    if not isinstance(class_node, ast.ClassDef):
        return {}
    lines = source.splitlines()
    descriptions: dict[str, str] = {}
    for node in class_node.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        leading: list[str] = []
        index = node.lineno - 2
        while index >= 0 and lines[index].strip().startswith("#"):
            leading.insert(0, lines[index].strip().lstrip("#").strip())
            index -= 1
        text = " ".join(part for part in leading if part)
        if not text and node.end_lineno is not None and node.end_col_offset is not None:
            tail = lines[node.end_lineno - 1][node.end_col_offset :]
            if "#" in tail:
                text = tail.split("#", 1)[1].strip()
        if text:
            descriptions[node.target.id] = text
    return descriptions


def _descriptions(cls: type) -> dict[str, str]:
    merged = _comment_descriptions(cls)
    merged.update(_docstring_attributes(cls))
    return merged


def _class_summary(cls: type) -> str:
    doc = inspect.getdoc(cls) or ""
    first = doc.split("\n\n", 1)[0].strip()
    return " ".join(first.split())


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def field_docs(cls: Any) -> list[FieldDoc]:
    """Field table rows for one dataclass, in declaration order."""
    hints = get_type_hints(cls, include_extras=True)
    descriptions = _descriptions(cls)
    rows: list[FieldDoc] = []
    for item in fields(cls):
        key = _yaml_key(item)
        if key is None:
            continue
        annotation = hints.get(item.name, item.type)
        rows.append(
            FieldDoc(
                key=key,
                type_label=_type_label(annotation),
                default=_default_label(item),
                description=descriptions.get(item.name, ""),
            )
        )
    return rows


# ---------------------------------------------------------------------------
# Internal fields: what the authoring vocabularies expand into
# ---------------------------------------------------------------------------


def _present(cls: type, keys: frozenset[str]) -> frozenset[str]:
    """Keep only the keys ``cls`` actually declares (TRT-LLM alone has ``*_extra_args``)."""
    declared = {row.key for row in field_docs(cls)}
    return frozenset(key for key in keys if key in declared)


# Engine dataclass -> yaml keys that are internal (the roles SrtConfig binds, the Mooncake
# block `services:` fills; never written on `engine`). Omitted from schema-reference.md.
INTERNAL_FIELDS: dict[type, frozenset[str]] = {
    cls: _present(cls, frozenset({"roles", "mooncake_kv_store"})) for _, cls in BACKEND_TYPES
}

# Top-level keys the loader gate refuses (the pre-2.0 `backend:` and `infra:`); not fields anymore,
# kept so the recipe table and the gate name the same keys.
INTERNAL_TOP_LEVEL: frozenset[str] = frozenset(LEGACY_TOP_LEVEL_KEYS)

# Dataclasses reachable only through internal keys.
INTERNAL_CLASSES: frozenset[type] = frozenset(
    {
        MooncakeKVStoreConfig,
        VLLMMooncakeKVStoreConfig,
    }
)


def _row(row: FieldDoc) -> str:
    return f"| `{row.key}` | {row.type_label} | {row.default} | {_cell(row.description)} |"


def _table_header() -> list[str]:
    return ["| Key | Type | Default | Description |", "|---|---|---|---|"]


def _render_table(cls: type) -> list[str]:
    """Field table for ``cls``: every field a recipe may write."""
    internal = INTERNAL_FIELDS.get(cls, frozenset())
    out = _table_header()
    for row in field_docs(cls):
        if row.key in internal:
            continue
        if cls is RoleConfig and row.key == "engine":
            row = FieldDoc(row.key, _ENGINE_ROW.type_label, row.default, row.description)
        out.append(_row(row))
    return out


def _render_top_level_table() -> list[str]:
    """The recipe's top-level keys: the dataclass fields minus the keys the loader gate refuses."""
    out = _table_header()
    for row in field_docs(SrtConfig):
        if row.key in INTERNAL_TOP_LEVEL:
            continue
        if row.key == "engine":
            row = _ENGINE_ROW
        elif row.key == "schema":
            row = FieldDoc(
                row.key,
                row.type_label,
                "required",
                "Recipe schema version. Every recipe declares `schema: 2`; a recipe without it is the pre-2.0 "
                "layout and does not load (see [legacy-v1.md](legacy-v1.md) and `srtctl migrate`).",
            )
        out.append(_row(row))
    return out


def _render_authoring_surface() -> list[str]:
    lines = [
        "## Authoring surface",
        "",
        (
            "Three vocabularies carry the engine, the topology, and the placement. `engine` and `roles` are "
            "fields of the recipe (the table above and [RoleConfig](#roleconfig) below); the engine dataclasses' "
            "per-mode fields are internal and receive each role's settings at load. The pre-2.0 layout no longer "
            "loads and is documented for migration in [legacy-v1.md](legacy-v1.md)."
        ),
        "",
        "### engine",
        "",
        "`engine: <type>` or `engine: {type: <type>, ...}`. `type` is one of "
        + ", ".join(f"`{name}`" for name, _ in BACKEND_TYPES)
        + "; the remaining keys are that engine's knobs, listed under [Engine types](#engine-types).",
        "Use either one top-level engine or an explicit engine on every role, never both. Role engines do not inherit options from each other.",
        "",
        "### roles",
        "",
        "`roles.<role>` for `" + "`, `".join(ROLE_NAMES) + "`. The `agg` role is the aggregated deployment; "
        "`prefill` and `decode` together are the disaggregated one. Each role is a [RoleConfig](#roleconfig): "
        "`nodes` (or `colocate` on decode, to share the prefill nodes), `workers`, `gpus`, `env`, `args`, and "
        "optionally its own `engine` and `container`.",
        "",
        "### placement",
        "",
    ]
    lines.extend(["| Key | Values | Default |", "|---|---|---|"])
    for key, values, default in _PLACEMENT_ROWS:
        lines.append(f"| `{key}` | {values} | {default} |")
    lines.extend(
        [
            "",
            (
                "`dedicated` reserves a node for that component. The discovery plane (etcd, NATS) is placed "
                "through its `services:` entries; see [services.md](services.md)."
            ),
            "",
        ]
    )
    return lines


def _nested_types(cls: Any) -> list[type]:
    hints = get_type_hints(cls, include_extras=True)
    found: list[type] = []
    for item in fields(cls):
        if _yaml_key(item) is None:
            continue
        for target in _dataclass_targets(hints.get(item.name, item.type)):
            if target not in found:
                found.append(target)
    return found


def _walk(root: type, skip: AbstractSet[type]) -> list[type]:
    """Breadth-first list of dataclasses reachable from ``root`` (root excluded)."""
    order: list[type] = []
    queue = [root]
    seen = {root}
    while queue:
        current = queue.pop(0)
        for nested in _nested_types(current):
            if nested in seen or nested in skip:
                continue
            seen.add(nested)
            order.append(nested)
            queue.append(nested)
    return order


def _render_class_section(cls: type, level: int) -> list[str]:
    heading = "#" * level
    lines = [f"{heading} {cls.__name__}", ""]
    summary = _class_summary(cls)
    if summary:
        lines.extend([summary, ""])
    lines.extend(_render_table(cls))
    lines.append("")
    return lines


def render_schema_reference() -> str:
    """Render the field-level reference for recipes and the cluster config."""
    lines: list[str] = [
        "# Schema Reference",
        "",
        GENERATED_NOTICE,
        "",
        (
            "Field-level reference for the recipe layout (`schema: 2`) and the cluster config "
            "`srtslurm.yaml` (`ClusterConfig`), generated from the dataclasses in `srtctl.core.schema` and "
            "`srtctl.backends`. Each table lists the YAML key, "
            "the type, the default (`required` when there is none), and a description taken from the class "
            "docstring or the comment on the field. Nested types link to their own table. The pre-2.0 (v1) "
            "layout no longer loads; its key-by-key mapping onto this layout is in [legacy-v1.md](legacy-v1.md) "
            "and `srtctl migrate` rewrites it. For prose, examples, and semantics see "
            "[config-reference.md](config-reference.md)."
        ),
        "",
        "## Recipe",
        "",
        "Top-level keys of a recipe YAML.",
        "",
    ]
    lines.extend(_render_top_level_table())
    lines.append("")
    lines.extend(_render_authoring_surface())

    hidden_classes = INTERNAL_CLASSES
    nested = [cls for cls in _walk(SrtConfig, skip=_BACKEND_CLASSES) if cls not in hidden_classes]
    if nested:
        lines.extend(["## Recipe sections", ""])
        for cls in nested:
            lines.extend(_render_class_section(cls, level=3))

    lines.extend(
        [
            "## Engine types",
            "",
            "`engine.type` selects one of the following; the remaining `engine` keys are that type's knobs.",
            "",
        ]
    )
    engine_nested: list[type] = []
    for type_name, cls in BACKEND_TYPES:
        lines.extend([f"### {cls.__name__}", "", f"`engine.type: {type_name}`", ""])
        summary = _class_summary(cls)
        if summary:
            lines.extend([summary, ""])
        lines.extend(_render_table(cls))
        lines.append("")
        for extra in _walk(cls, skip=_BACKEND_CLASSES | set(nested)):
            if extra not in engine_nested and extra not in hidden_classes:
                engine_nested.append(extra)
    for cls in engine_nested:
        lines.extend(_render_class_section(cls, level=3))

    lines.extend(
        [
            "## Cluster config",
            "",
            "Top-level keys of `srtslurm.yaml`. Recipes inherit these defaults and resolve aliases through them.",
            "",
        ]
    )
    lines.extend(_render_table(ClusterConfig))
    lines.append("")
    for cls in _walk(ClusterConfig, skip=_BACKEND_CLASSES | set(nested) | set(engine_nested)):
        lines.extend(_render_class_section(cls, level=3))

    return "\n".join(lines).rstrip() + "\n"


def write_schema_reference(output: Path = DEFAULT_OUTPUT) -> Path:
    """Write the rendered document; return its path."""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_schema_reference(), encoding="utf-8")
    return output


def schema_reference_is_current(output: Path = DEFAULT_OUTPUT) -> bool:
    """True when the checked-in file matches what the code renders."""
    return output.exists() and output.read_text(encoding="utf-8") == render_schema_reference()
