# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate ``docs/schema-reference.md`` and ``docs/legacy-v1.md`` from the code.

The recipe schema is the dataclass tree rooted at :class:`SrtConfig`; the
cluster config (``srtslurm.yaml``) is :class:`ClusterConfig`. This module walks
both and renders one Markdown table per dataclass, so the field-level reference
cannot drift from the code: both checked-in files are regenerated by
``srtctl schema-docs`` and CI fails when either is stale.

Two documents come out of one walk:

* ``schema-reference.md`` describes the 2.0 authoring surface only: the
  top-level ``engine:``, ``roles:``, and ``placement:`` vocabularies (from
  :mod:`srtctl.core.roles` and :mod:`srtctl.core.placement`) plus every
  dataclass field that is not a v1 spelling.
* ``legacy-v1.md`` is the single place the v1 layout is documented: the
  internal fields the 2.0 vocabularies normalize into, what each one became,
  and the classes that only exist for v1 recipes (``infra``, ``backend``,
  per-mode ``*_environment`` / ``<engine>_config``, ``mooncake_kv_store``).

Which fields are legacy is declared once in :data:`LEGACY_FIELDS`, derived from
the same constants the migrator uses (role names, engine config keys, placement
fields), and :mod:`tests.test_schema_docs` proves ``srtctl migrate`` removes
every one of them.

Descriptions come from two places, in priority order: an ``Attributes:`` block
in the class docstring (Google style), then the ``#`` comment block directly
above a field or the trailing comment on its line.
"""

from __future__ import annotations

import ast
import inspect
import re
import textwrap
import types
from collections.abc import Set as AbstractSet
from dataclasses import MISSING, Field, dataclass, fields, is_dataclass
from pathlib import Path
from typing import Annotated, Any, Literal, get_args, get_origin, get_type_hints

from srtctl.backends import (
    AtomProtocol,
    AtomServerConfig,
    MockerProtocol,
    MockerServerConfig,
    SGLangProtocol,
    SGLangServerConfig,
    TRTLLMProtocol,
    TRTLLMServerConfig,
    VLLMProtocol,
    VLLMServerConfig,
)
from srtctl.backends.sglang import MooncakeKVStoreConfig
from srtctl.backends.vllm import VLLMMooncakeKVStoreConfig
from srtctl.core.config import SCHEMA1_FRONTEND_RENAMES
from srtctl.core.placement import _BENCHMARK as _BENCHMARK_PLACEMENT_FIELDS
from srtctl.core.placement import _FRONTEND as _FRONTEND_PLACEMENT_FIELDS
from srtctl.core.roles import COLOCATE, ENGINE_CONFIG_KEY, ROLE_NAMES, ROLE_TO_MODE
from srtctl.core.schema import (
    BenchmarkConfig,
    ClusterConfig,
    DynamoConfig,
    FrontendConfig,
    InfraConfig,
    ResourceConfig,
    SrtConfig,
)

_DOCS_DIR = Path(__file__).resolve().parents[3] / "docs"
DEFAULT_OUTPUT = _DOCS_DIR / "schema-reference.md"
DEFAULT_LEGACY_OUTPUT = _DOCS_DIR / "legacy-v1.md"

GENERATED_NOTICE = (
    "<!-- GENERATED FILE. Do not edit by hand. Regenerate with `srtctl schema-docs`; "
    "CI fails when this file is stale. -->"
)

# backend.type value -> dataclass. Order is the documentation order.
BACKEND_TYPES: tuple[tuple[str, type], ...] = (
    ("atom", AtomProtocol),
    ("sglang", SGLangProtocol),
    ("trtllm", TRTLLMProtocol),
    ("vllm", VLLMProtocol),
    ("mocker", MockerProtocol),
)
_BACKEND_CLASSES: set[type] = {cls for _, cls in BACKEND_TYPES}


@dataclass(frozen=True)
class FieldDoc:
    """One row of a field table."""

    key: str
    type_label: str
    default: str
    description: str


_V2_TOP_LEVEL_ROWS = (
    FieldDoc(
        key="engine",
        type_label="str \\| mapping",
        default="required",
        description=(
            "The engine type (`atom`, `sglang`, `trtllm`, `vllm`, `mocker`) as a string, or a mapping with `type` "
            "plus the engine-wide knobs listed under [Engine types](#engine-types)."
        ),
    ),
    FieldDoc(
        key="roles",
        type_label="mapping of role -> [Role](#roles)",
        default="required",
        description="One block per worker role (`prefill`, `decode`, `agg`): topology, env, and engine args.",
    ),
)

# Per-role keys of the roles: block (srtctl.core.roles._ROLE_SPEC_KEYS), in documentation order.
_ROLE_ROWS: tuple[tuple[str, str, str, str], ...] = (
    (
        "nodes",
        "int \\| `colocate`",
        "required",
        (
            "Nodes reserved for this role. `colocate` (decode only) reserves none and packs the decode workers "
            "onto the prefill nodes' free GPUs; `gpus` is then required on both roles and the loader rejects "
            "a split that does not fit."
        ),
    ),
    ("workers", "int", "required", "Number of workers of this role."),
    (
        "gpus",
        "int",
        "`nodes * gpus_per_node // workers`",
        "GPUs per worker. Required when decode colocates.",
    ),
    ("env", "dict[str, str]", "`{}`", "Environment for every worker of this role."),
    ("args", "mapping", "`{}`", "The engine's own CLI flags for this role, as a mapping (`tensor-parallel-size: 4`)."),
    ("extra_args", "list[str]", "`[]`", "Raw extra CLI arguments (TRT-LLM)."),
    ("engine", "str", "top-level `engine`", "Optional; must equal the top-level engine type."),
    (
        "kv_events",
        "bool \\| mapping",
        "`None`",
        "`true` for the default ZMQ publisher, or a mapping with `publisher` / `topic`.",
    ),
    ("sidecar", "bool", "`False`", "Run the native engine with a Dynamo sidecar; every role must agree."),
    (
        "critical",
        "bool",
        "`True`",
        "A worker of this role exiting fails the run. `false` keeps the run alive for probes that kill workers.",
    ),
)

_PLACEMENT_ROWS: tuple[tuple[str, str, str], ...] = (
    ("frontend.placement.node", "`head` \\| `first_decode` \\| `dedicated`", "`head`"),
    ("benchmark.placement.node", "`head` \\| `last_decode` \\| `dedicated`", "`head`"),
    (
        "services[].placement.node",
        "`head` \\| `infra` \\| `dedicated` \\| `prefill` \\| `decode` \\| `agg` \\| `workers`",
        "type default",
    ),
)


# ---------------------------------------------------------------------------
# Type introspection
# ---------------------------------------------------------------------------


def _is_dataclass_type(obj: Any) -> bool:
    return isinstance(obj, type) and is_dataclass(obj)


def _dataclass_targets(annotation: Any) -> list[type]:
    """Dataclass types reachable from an annotation (through Annotated, unions, containers)."""
    if annotation is None:
        return []
    if _is_dataclass_type(annotation):
        return [annotation]
    origin = get_origin(annotation)
    if origin is None:
        return []
    found: list[type] = []
    for arg in get_args(annotation):
        for target in _dataclass_targets(arg):
            if target not in found:
                found.append(target)
    return found


def _type_label(annotation: Any) -> str:
    """Human-readable type, with dataclasses linked to their section."""
    if annotation is None:
        return "unknown"
    if annotation is type(None):
        return "None"
    if _is_dataclass_type(annotation):
        return f"[{annotation.__name__}](#{annotation.__name__.lower()})"
    origin = get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))
    if origin is Annotated:  # identity check: str(origin) differs across Python versions
        return _type_label(get_args(annotation)[0])
    if origin is Literal:
        return "one of " + ", ".join(f"`{value!r}`" for value in get_args(annotation))
    if origin is types.UnionType or str(origin) == "typing.Union":
        return " \\| ".join(_type_label(arg) for arg in get_args(annotation))
    args = get_args(annotation)
    origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
    if not args:
        return origin_name
    if origin is tuple and len(args) == 2 and args[1] is Ellipsis:
        return f"tuple[{_type_label(args[0])}, ...]"
    return f"{origin_name}[{', '.join(_type_label(arg) for arg in args)}]"


def _yaml_key(item: Field) -> str | None:
    """The key a recipe author writes, or None when the field is not user-facing."""
    marshmallow_field = item.metadata.get("marshmallow_field")
    data_key = getattr(marshmallow_field, "data_key", None) if marshmallow_field is not None else None
    if data_key:
        return str(data_key)
    if item.name.startswith("_"):
        return None
    return item.name


def _default_label(item: Field) -> str:
    if item.default is not MISSING:
        return f"`{item.default!r}`"
    if item.default_factory is not MISSING:  # type: ignore[attr-defined]
        factory = item.default_factory  # type: ignore[attr-defined]
        if factory in (dict, list, tuple, set, frozenset):
            return f"`{factory()!r}`"
        name = getattr(factory, "__name__", type(factory).__name__)
        return f"`{name}()`"
    return "required"


# ---------------------------------------------------------------------------
# Descriptions from docstrings and source comments
# ---------------------------------------------------------------------------

_ATTRIBUTE_LINE = re.compile(r"^\s{1,8}([A-Za-z_]\w*)\s*(?:\([^)]*\))?:\s*(.*)$")


def _docstring_attributes(cls: type) -> dict[str, str]:
    """Parse a Google-style ``Attributes:`` block into {field: description}."""
    doc = inspect.getdoc(cls) or ""
    match = re.search(r"^Attributes:\s*$", doc, re.MULTILINE)
    if match is None:
        return {}
    descriptions: dict[str, str] = {}
    current: str | None = None
    for line in doc[match.end() :].splitlines():
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if indent == 0:
            break
        attribute = _ATTRIBUTE_LINE.match(line)
        if attribute and indent <= 4:
            current = attribute.group(1)
            descriptions[current] = attribute.group(2).strip()
        elif current:
            descriptions[current] = f"{descriptions[current]} {line.strip()}".strip()
    return descriptions


def _comment_descriptions(cls: type) -> dict[str, str]:
    """Comment block above each field, or the trailing comment on its line."""
    try:
        source = textwrap.dedent(inspect.getsource(cls))
    except (OSError, TypeError):
        return {}
    try:
        class_node = ast.parse(source).body[0]
    except (SyntaxError, IndexError):
        return {}
    if not isinstance(class_node, ast.ClassDef):
        return {}
    lines = source.splitlines()
    descriptions: dict[str, str] = {}
    for node in class_node.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        leading: list[str] = []
        index = node.lineno - 2
        while index >= 0 and lines[index].strip().startswith("#"):
            leading.insert(0, lines[index].strip().lstrip("#").strip())
            index -= 1
        text = " ".join(part for part in leading if part)
        if not text and node.end_lineno is not None and node.end_col_offset is not None:
            tail = lines[node.end_lineno - 1][node.end_col_offset :]
            if "#" in tail:
                text = tail.split("#", 1)[1].strip()
        if text:
            descriptions[node.target.id] = text
    return descriptions


def _descriptions(cls: type) -> dict[str, str]:
    merged = _comment_descriptions(cls)
    merged.update(_docstring_attributes(cls))
    return merged


def _class_summary(cls: type) -> str:
    doc = inspect.getdoc(cls) or ""
    first = doc.split("\n\n", 1)[0].strip()
    return " ".join(first.split())


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def field_docs(cls: Any) -> list[FieldDoc]:
    """Field table rows for one dataclass, in declaration order."""
    hints = get_type_hints(cls, include_extras=True)
    descriptions = _descriptions(cls)
    rows: list[FieldDoc] = []
    for item in fields(cls):
        key = _yaml_key(item)
        if key is None:
            continue
        annotation = hints.get(item.name, item.type)
        rows.append(
            FieldDoc(
                key=key,
                type_label=_type_label(annotation),
                default=_default_label(item),
                description=descriptions.get(item.name, ""),
            )
        )
    return rows


# ---------------------------------------------------------------------------
# The v1 / 2.0 partition
# ---------------------------------------------------------------------------


def _role_legacy_fields() -> dict[str, str]:
    """``resources.<role>_nodes`` and friends -> their ``roles.<role>.*`` spelling."""
    out: dict[str, str] = {}
    for role in ROLE_NAMES:
        out[f"{role}_nodes"] = f"`roles.{role}.nodes`" + (
            f" (`{COLOCATE}` replaces the `0` sentinel)" if role == "decode" else ""
        )
        out[f"{role}_workers"] = f"`roles.{role}.workers`"
        out[f"gpus_per_{role}"] = f"`roles.{role}.gpus`"
    return out


def _backend_legacy_fields(engine_key: str) -> dict[str, str]:
    """Per-mode ``backend`` fields -> their ``roles.<role>.*`` spelling, for one engine's config key."""
    out: dict[str, str] = {}
    for role in ROLE_NAMES:
        mode = ROLE_TO_MODE[role]
        out[f"{mode}_environment"] = f"`roles.{role}.env`"
        out[f"{mode}_extra_args"] = f"`roles.{role}.extra_args`"
    out[engine_key] = "`roles.<role>.args` (one mapping per role; the `prefill` / `decode` / `aggregated` keys)"
    out["kv_events_config"] = "`roles.<role>.kv_events`"
    out["mooncake_kv_store"] = (
        "a `services:` entry of type `mooncake-master` plus the worker env on `roles.<role>.env` "
        "(see [mooncake-kv-store.md](mooncake-kv-store.md))"
    )
    return out


def _present(cls: type, mapping: dict[str, str]) -> dict[str, str]:
    """Keep only the keys ``cls`` actually declares (TRT-LLM alone has ``*_extra_args``)."""
    keys = {row.key for row in field_docs(cls)}
    return {key: value for key, value in mapping.items() if key in keys}


# dataclass -> {yaml key: what the 2.0 layout writes instead}. A key listed here is
# omitted from schema-reference.md and documented in legacy-v1.md.
LEGACY_FIELDS: dict[type, dict[str, str]] = {
    ResourceConfig: _role_legacy_fields(),
    FrontendConfig: {
        _FRONTEND_PLACEMENT_FIELDS[0]: "`frontend.placement.node: <location>`",
        _FRONTEND_PLACEMENT_FIELDS[1]: "`frontend.placement.node: dedicated`",
    },
    BenchmarkConfig: {
        _BENCHMARK_PLACEMENT_FIELDS[0]: "`benchmark.placement.node: <location>`",
        _BENCHMARK_PLACEMENT_FIELDS[1]: "`benchmark.placement.node: dedicated`",
    },
    DynamoConfig: {
        "version": "`dynamo.source.pypi`",
        "wheel": "`dynamo.source.wheel`",
        "hash": "`dynamo.source.git` + `dynamo.source.rev` (a commit)",
        "top_of_tree": "`dynamo.source.git` + `dynamo.source.top_of_tree: true`",
        "cargo_patches": "`dynamo.source.patches`",
    },
    SGLangProtocol: _present(SGLangProtocol, _backend_legacy_fields(ENGINE_CONFIG_KEY["sglang"])),
    TRTLLMProtocol: _present(TRTLLMProtocol, _backend_legacy_fields(ENGINE_CONFIG_KEY["trtllm"])),
    VLLMProtocol: _present(VLLMProtocol, _backend_legacy_fields(ENGINE_CONFIG_KEY["vllm"])),
    MockerProtocol: _present(MockerProtocol, _backend_legacy_fields(ENGINE_CONFIG_KEY["mocker"])),
}

# Top-level recipe keys that only exist in the v1 layout.
LEGACY_TOP_LEVEL: dict[str, str] = {
    "backend": "`engine:` (the type, plus engine-wide knobs) and `roles.<role>.args` / `.env`",
    "infra": "`services:` entries of type `etcd` and `nats` (`placement.node: dedicated`, `options.max_payload_mb`)",
}

# Dataclasses that are reachable only through legacy keys.
LEGACY_CLASSES: frozenset[type] = frozenset(
    {
        InfraConfig,
        SGLangServerConfig,
        TRTLLMServerConfig,
        VLLMServerConfig,
        MockerServerConfig,
        MooncakeKVStoreConfig,
        VLLMMooncakeKVStoreConfig,
    }
)

# New options are documented through v2 services, not legacy runtime tables.
_V2_SERVICE_OPTION_FIELDS: dict[type, frozenset[str]] = {
    VLLMMooncakeKVStoreConfig: frozenset({"device_names_by_gpu"}),
}

# ATOM was added in v2; its normalized role fields are internal, not v1 API.
INTERNAL_FIELDS = {AtomProtocol: _present(AtomProtocol, _backend_legacy_fields(ENGINE_CONFIG_KEY["atom"]))}
INTERNAL_CLASSES = frozenset({AtomServerConfig})


def _row(row: FieldDoc) -> str:
    return f"| `{row.key}` | {row.type_label} | {row.default} | {_cell(row.description)} |"


def _table_header() -> list[str]:
    return ["| Key | Type | Default | Description |", "|---|---|---|---|"]


def _legacy_keys(cls: type) -> set[str]:
    return set(LEGACY_FIELDS.get(cls, {}))


def _render_table(cls: type, *, only_legacy: bool = False) -> list[str]:
    """Field table for ``cls``: the 2.0 rows by default, or only the v1 rows."""
    legacy = _legacy_keys(cls)
    out = _table_header()
    for row in field_docs(cls):
        if row.key in _V2_SERVICE_OPTION_FIELDS.get(cls, ()) or row.key in INTERNAL_FIELDS.get(cls, {}):
            continue
        if (row.key in legacy) == only_legacy:
            out.append(_row(row))
    return out


def _render_top_level_table() -> list[str]:
    """The recipe's top-level keys in the 2.0 layout: dataclass fields minus v1 keys, plus engine/roles."""
    out = _table_header()
    for row in field_docs(SrtConfig):
        if row.key in LEGACY_TOP_LEVEL:
            continue
        if row.key == "schema":
            row = FieldDoc(row.key, row.type_label, "`2`", "Recipe schema version. Write `schema: 2` for this layout.")
        out.append(_row(row))
        if row.key == "resources":
            out.extend(_row(v2) for v2 in _V2_TOP_LEVEL_ROWS)
    return out


def _render_authoring_surface() -> list[str]:
    lines = [
        "## Authoring surface",
        "",
        (
            "Three vocabularies are specific to the 2.0 layout. They are normalized into the internal fields "
            "before validation (see [legacy-v1.md](legacy-v1.md) for those fields), so they are exactly "
            "equivalent to the v1 spelling and cannot be combined with it for the same block."
        ),
        "",
        "### engine",
        "",
        "`engine: <type>` or `engine: {type: <type>, ...}`. `type` is one of "
        + ", ".join(f"`{name}`" for name, _ in BACKEND_TYPES)
        + "; the remaining keys are that engine's knobs, listed under [Engine types](#engine-types).",
        "",
        "### roles",
        "",
        "`roles.<role>` for `" + "`, `".join(ROLE_NAMES) + "`. The `agg` role is the aggregated deployment.",
        "",
    ]
    lines.extend(_table_header())
    for key, type_label, default, description in _ROLE_ROWS:
        lines.append(f"| `{key}` | {type_label} | {default} | {_cell(description)} |")
    lines.extend(["", "### placement", ""])
    lines.extend(["| Key | Values | Default |", "|---|---|---|"])
    for key, values, default in _PLACEMENT_ROWS:
        lines.append(f"| `{key}` | {values} | {default} |")
    lines.extend(
        [
            "",
            (
                "`dedicated` reserves a node for that component. The discovery plane (etcd, NATS) is placed "
                "through its `services:` entries; see [services.md](services.md)."
            ),
            "",
        ]
    )
    return lines


def _nested_types(cls: Any) -> list[type]:
    hints = get_type_hints(cls, include_extras=True)
    found: list[type] = []
    for item in fields(cls):
        if _yaml_key(item) is None:
            continue
        for target in _dataclass_targets(hints.get(item.name, item.type)):
            if target not in found:
                found.append(target)
    return found


def _walk(root: type, skip: AbstractSet[type]) -> list[type]:
    """Breadth-first list of dataclasses reachable from ``root`` (root excluded)."""
    order: list[type] = []
    queue = [root]
    seen = {root}
    while queue:
        current = queue.pop(0)
        for nested in _nested_types(current):
            if nested in seen or nested in skip:
                continue
            seen.add(nested)
            order.append(nested)
            queue.append(nested)
    return order


def _render_class_section(cls: type, level: int, *, only_legacy: bool = False) -> list[str]:
    heading = "#" * level
    lines = [f"{heading} {cls.__name__}", ""]
    summary = _class_summary(cls)
    if summary:
        lines.extend([summary, ""])
    lines.extend(_render_table(cls, only_legacy=only_legacy))
    lines.append("")
    return lines


def render_schema_reference() -> str:
    """Render the 2.0 field-level reference for recipes and the cluster config."""
    lines: list[str] = [
        "# Schema Reference",
        "",
        GENERATED_NOTICE,
        "",
        (
            "Field-level reference for the 2.0 recipe layout (`schema: 2`) and the cluster config "
            "`srtslurm.yaml` (`ClusterConfig`), generated from `srtctl.core.roles`, `srtctl.core.placement`, "
            "and the dataclasses in `srtctl.core.schema` and `srtctl.backends`. Each table lists the YAML key, "
            "the type, the default (`required` when there is none), and a description taken from the class "
            "docstring or the comment on the field. Nested types link to their own table. The v1 layout and "
            "the internal fields it maps onto are documented in [legacy-v1.md](legacy-v1.md); for prose, "
            "examples, and semantics see [config-reference.md](config-reference.md)."
        ),
        "",
        "## Recipe",
        "",
        "Top-level keys of a recipe YAML.",
        "",
    ]
    lines.extend(_render_top_level_table())
    lines.append("")
    lines.extend(_render_authoring_surface())

    hidden_classes = LEGACY_CLASSES | INTERNAL_CLASSES
    nested = [cls for cls in _walk(SrtConfig, skip=_BACKEND_CLASSES) if cls not in hidden_classes]
    if nested:
        lines.extend(["## Recipe sections", ""])
        for cls in nested:
            lines.extend(_render_class_section(cls, level=3))

    lines.extend(
        [
            "## Engine types",
            "",
            "`engine.type` selects one of the following; the remaining `engine` keys are that type's knobs.",
            "",
        ]
    )
    engine_nested: list[type] = []
    for type_name, cls in BACKEND_TYPES:
        lines.extend([f"### {cls.__name__}", "", f"`engine.type: {type_name}`", ""])
        summary = _class_summary(cls)
        if summary:
            lines.extend([summary, ""])
        lines.extend(_render_table(cls))
        lines.append("")
        for extra in _walk(cls, skip=_BACKEND_CLASSES | set(nested)):
            if extra not in engine_nested and extra not in hidden_classes:
                engine_nested.append(extra)
    for cls in engine_nested:
        lines.extend(_render_class_section(cls, level=3))

    lines.extend(
        [
            "## Cluster config",
            "",
            "Top-level keys of `srtslurm.yaml`. Recipes inherit these defaults and resolve aliases through them.",
            "",
        ]
    )
    lines.extend(_render_table(ClusterConfig))
    lines.append("")
    for cls in _walk(ClusterConfig, skip=_BACKEND_CLASSES | set(nested) | set(engine_nested)):
        lines.extend(_render_class_section(cls, level=3))

    return "\n".join(lines).rstrip() + "\n"


def render_legacy_reference() -> str:
    """Render the single document for the v1 recipe layout."""
    lines: list[str] = [
        "# Legacy (v1) recipe layout",
        "",
        GENERATED_NOTICE,
        "",
        (
            "Recipes without `schema: 2` (or with `schema: 1`) use the pre-2.0 layout: worker topology under "
            "`resources`, the engine and its per-mode settings under `backend`, the discovery plane under "
            "`infra`, and placement as per-block booleans. Every field below still loads, because the 2.0 "
            "vocabularies (`engine:`, `roles:`, `placement:`, `services:`, `dynamo.source`) are normalized "
            "into exactly these fields before validation. Nothing here should appear in a new recipe: "
            "`srtctl migrate -f <recipe> --in-place` rewrites it, preserving comments and key order, and "
            "`srtctl migrate --verify -f <path>` proves the v1 and migrated documents resolve to the same "
            "config. The 2.0 layout is documented in [schema-reference.md](schema-reference.md) and "
            "[config-reference.md](config-reference.md)."
        ),
        "",
        "## v1 keys and what replaced them",
        "",
        "| v1 key | 2.0 spelling |",
        "|---|---|",
    ]
    for key, replacement in LEGACY_TOP_LEVEL.items():
        lines.append(f"| `{key}` (top level) | {_cell(replacement)} |")
    section_names = {
        ResourceConfig: "resources",
        FrontendConfig: "frontend",
        BenchmarkConfig: "benchmark",
        DynamoConfig: "dynamo",
    }
    for cls, prefix in section_names.items():
        for key, replacement in LEGACY_FIELDS[cls].items():
            lines.append(f"| `{prefix}.{key}` | {_cell(replacement)} |")
    backend_rows: dict[str, str] = {}
    for _, cls in BACKEND_TYPES:
        for key, replacement in LEGACY_FIELDS.get(cls, {}).items():
            backend_rows.setdefault(key, replacement)
    for key, replacement in backend_rows.items():
        lines.append(f"| `backend.{key}` | {_cell(replacement)} |")
    lines.append("")

    lines.extend(
        [
            "## v1 values that changed meaning",
            "",
            (
                "These keys exist in both layouts, but the value means something else in 2.0. A schema 1 recipe "
                "keeps its historical meaning at load; `srtctl migrate` writes the 2.0 spelling."
            ),
            "",
            "| Key | schema 1 value | 2.0 spelling | 2.0 meaning of the old value |",
            "|---|---|---|---|",
        ]
    )
    for old_value, new_value in SCHEMA1_FRONTEND_RENAMES.items():
        lines.append(
            f"| `frontend.type` | `{old_value}` (the SGLang Model Gateway router) | `{new_value}` | "
            f"`{old_value}` is the router-free single `sglang.launch_server` worker |"
        )
    lines.append("")

    lines.extend(["## Legacy fields in retained sections", ""])
    for cls, prefix in section_names.items():
        lines.extend([f"### {prefix} ({cls.__name__})", ""])
        lines.extend(_render_table(cls, only_legacy=True))
        lines.append("")

    lines.extend(
        [
            "## backend",
            "",
            (
                "`backend.type` selected the engine; the 2.0 layout writes `engine:` instead and moves the "
                "per-mode keys below onto `roles.<role>`. The engine-wide knobs (everything not listed here) are "
                "unchanged and documented under Engine types in "
                "[schema-reference.md](schema-reference.md#engine-types)."
            ),
            "",
        ]
    )
    server_configs: list[type] = []
    for type_name, cls in BACKEND_TYPES:
        if cls not in LEGACY_FIELDS:
            continue
        lines.extend([f"### {cls.__name__}", "", f"`backend.type: {type_name}`", ""])
        lines.extend(_render_table(cls, only_legacy=True))
        lines.append("")
        for extra in _walk(cls, skip=_BACKEND_CLASSES):
            if extra in LEGACY_CLASSES and extra not in server_configs:
                server_configs.append(extra)
    for cls in server_configs:
        lines.extend(_render_class_section(cls, level=3))

    lines.extend(["## infra", ""])
    lines.extend(_render_class_section(InfraConfig, level=3))

    return "\n".join(lines).rstrip() + "\n"


def legacy_output_for(output: Path) -> Path:
    """The legacy document that accompanies a schema reference written to ``output``."""
    return output.parent / DEFAULT_LEGACY_OUTPUT.name


def write_schema_reference(output: Path = DEFAULT_OUTPUT, legacy_output: Path | None = None) -> Path:
    """Write both rendered documents; return the schema reference path."""
    legacy_output = legacy_output or legacy_output_for(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_schema_reference(), encoding="utf-8")
    legacy_output.parent.mkdir(parents=True, exist_ok=True)
    legacy_output.write_text(render_legacy_reference(), encoding="utf-8")
    return output


def schema_reference_is_current(output: Path = DEFAULT_OUTPUT, legacy_output: Path | None = None) -> bool:
    """True when both checked-in files match what the code renders."""
    legacy_output = legacy_output or legacy_output_for(output)
    if not output.exists() or not legacy_output.exists():
        return False
    return (
        output.read_text(encoding="utf-8") == render_schema_reference()
        and legacy_output.read_text(encoding="utf-8") == render_legacy_reference()
    )
